### ISSUE TITLE
Add Titan Graph DB to Flux

### ISSUE THREAD

**Issue by cfregly** [fluxcapacitor/pipeline#20]

**Comment by BrentDorsey** [comment]
Chris,

I have Titan:Db working in my local pipeline, haven’t done much with data but it’s working with Cassandra and with gremlin-server.

What do you think about changing the pipeline docker contain shared volume to the root of the pipeline folder instead of using data_work?  I been looking for a good way to test changes without having to commit to the git repo so locally I removed the git clone and pull code from the DockerFile and moved the sbt build code out of the DockerFile and into SOURCEME_FIRST.sh.

Cool benefits:

  *   Code changes made locally in your Mac OS are immediately available in the docker container!
  *   Reduced network traffic, git clone and pull no longer needed
  *   The DockerFile is strictly used for software installs, path variables and ports

Gotcha’s:

  *   Eclipse and other IDE’s with auto saving functionality have to be closed before the docker container is started to ensure files aren’t locked.  First time I tried it Cassandra wouldn’t start because the Eclipse had locks on the data directory.

Also, would you be interested in implementing twitter’s hfs-du<https://github.com/twitter/hdfs-du> in the pipeline?  A work we’ve been looking for a good way to monitor HDFS cluster usage that doesn’t consume a ton of resources.  Using the offline file viewer to copy the fsimage is the best way I’ve found.  I got everything working except the website, for some reason even though I exposed the port in the DockerFile and on the VM, the sites not available?

Are you going to Spark Summit East in New York in Feb?

Ciao,

Brent

**Comment by cfregly** [comment]
@BrentDorsey any update on the titandb pull request?

i recently added it to the Dockerfile, but haven't done much to configure it.  wasn't as simple as i thought it was going to be, but maybe i'm missing something.

any help getting it configured and running would be great! 

-chris

**Comment by BrentDorsey** [comment]
Sorry for the delayed response I’ve been heads down on a project for work.  Did you get the titan config working?  I’ll take a look today and compare the current branch to my local changes.

**Comment by cfregly** [comment]
@BrentDorsey talk to me, goose!  need your configs.  :)
