### ISSUE TITLE
Metastore 2.1.1 image is failing to pull on master

### ISSUE THREAD

**Issue by drathm** [fluxcapacitor/pipeline#215]
Could you push the latest metastore image? It looks like Monday's update is missing the corresponding docker image.

Error from pod:

Failed to pull image "docker.io/fluxcapacitor/metastore-2.1.1:master": image pull failed for docker.io/fluxcapacitor/metastore-2.1.1:master, this may be because there are no credentials on this request. details: (Error: image fluxcapacitor/metastore-2.1.1:master not found)
Error syncing pod, skipping: failed to "StartContainer" for "metastore-2-1-1" with ErrImagePull: "image pull failed for docker.io/fluxcapacitor/metastore-2.1.1:master, this may be because there are no credentials on this request. details: (Error: image fluxcapacitor/metastore-2.1.1:master not found)"

**Comment by cfregly** [comment]
will do.  pardon our dust!  :)

**Comment by cfregly** [comment]
ok, i pushed both master and v1.0.0:  https://hub.docker.com/r/fluxcapacitor/metastore-2.1.1/tags/

oh, and as part of monday's update, we're encouraging people to use v1.0.0 (stable) instead of master (unstable).

this is reflected in the wiki setup notes:  https://github.com/fluxcapacitor/pipeline/wiki/Setup-Pipeline-on-Kubernetes#deploy-pipelineio-services.

Notice the yaml is now pulling from the v1.0.0 tag.  

ie. https://raw.githubusercontent.com/fluxcapacitor/pipeline/v1.0.0/metastore.ml/metastore-rc.yaml

we had a small issue that i just fixed, but i just re-tagged/re-pushed and things look good.

let us know if you're still having issues.

thanks, @drathm !
