### ISSUE TITLE
Volume mounts for hdfs 

### ISSUE THREAD

**Issue by y2kbowen** [fluxcapacitor/pipeline#249]
I am uncertain if I am setting up my persistent stores correctly for hdfs.  I updated he yaml to use my nfs volume and PVC.  I mounted it at /root/volume.  The service comes up but it looks like the data is not configured there as I see nothing on my  nfs volume.   It looks like it is using my vms disk.  Could the yaml mount point be wrong?  Also I wasn't sure what the commented out configuration mount might be used for

**Comment by BrentDorsey** [comment]
KenB,

In order to use the commented hadoop-conf-dev-volume<https://github.com/fluxcapacitor/source.ml/blob/master/hdfs.ml/namenode-deploy.yaml#L36-L37> configuration you need to setup a Kubernetes secret named hadoop-conf-dev containing your hdfs configuration (core-site.xml<https://github.com/fluxcapacitor/pipeline/blob/master/hdfs.ml/etc/hadoop/core-site.xml> and hdfs-site.xml<https://github.com/fluxcapacitor/pipeline/blob/master/hdfs.ml/etc/hadoop/hdfs-site.xml>).

Executing the command below from the root of your pipeline<https://github.com/fluxcapacitor/pipeline> project will create a Kubernetes secret containing the contents of core-site.xml<https://github.com/fluxcapacitor/pipeline/blob/master/hdfs.ml/etc/hadoop/core-site.xml> and hdfs-site.xml<https://github.com/fluxcapacitor/pipeline/blob/master/hdfs.ml/etc/hadoop/hdfs-site.xml>

kubectl create secret generic hadoop-conf-dev --from-file=hdfs.ml/etc/hadoop

[cid:image001.png@01D3116A.7BB01820]

**Comment by cfregly** [comment]
closing.  please re-open if still an issue.
