### ISSUE TITLE
[Demo] HTML-based Image classification using TensorFlow using uploaded image

### ISSUE THREAD

**Issue by cfregly** [fluxcapacitor/pipeline#93]

**Comment by andyzeli** [comment]
pulled Changes:

combined the upload and url demo,
added two css files and a material design js file
Updated the server file to enable Xss and such: because I cant intergrate locally there are a few things to note:
 1. the classify command is commented out in favor of a fake command. just uncomment to return
2.  accordingly, the json dump is faked to match the fake command
3. data.results changed to data just for testing

need to pip install flask-cors in order for it to work.

I created a new folder called classifyDemo with the new files for clarity. we will of course have to make sure the html files point to the right scripts.

also, in the html file the url param of ajax request has http://localhost:5070/upload. need to update that

**Comment by cfregly** [comment]
part of larger demo-building effort underway.
